### ISSUE TITLE
About—  Typos

### ISSUE THREAD

**Issue by MarcAst24** [GeoDaCenter/chicago-environment-explorer#103]
**Issue**: Typos are present, especially when spelling ‘ChiVes’

**Recommendation**: Fix typos such as ‘Chivesemerged’ to ‘ChiVes emerged’ and ‘Chives is funded by NASA’ to ‘ChiVes is funded by NASA’’

**Rationale**: Consistency

**Comment by mradamcox** [comment]
Note: The italic style was causing an erasure of the space after _Chives_, making it look like "Chivesemerged". I'm just going to remove italic from this page entirely, we can address it's reintroduction later if necessary.
