### ISSUE TITLE
Swap displacement index with new source

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/chicago-environment-explorer#117]
DePaul team will add new displacement index source that shows better variability/variation across the city.

@dajoin-williams, you can add the index using the data contribution instructions here: https://docs.google.com/document/d/12lwkCAXxI9eW4Mdf6gaeR6LCsaNI3E0E6xvi7dqXr9k/edit#heading=h.l1v8ypz3kdpr 

This publishes the data as a google spreadsheet, with the join key = geoid (should be the 10-digit FIPS code)

You will also need to generate a new metadata google doc, and can use the previous one as a guide: https://docs.google.com/document/d/12LnNSq__94Aw-Twohb3ILmrGdtad6s77MO_gALS_Yzc/edit?usp=sharing

When complete, you can use this form to submit all the materials at once: https://docs.google.com/forms/d/e/1FAIpQLSdu5zCJcvLXp8eY0p3jLuCWPKSuGHjrw2auO3BsD57ssH4_wA/viewform 

When complete, please tag @Makosak and @mradamcox so we can review, and start the process of swapping displacement index.

**Comment by MStuhlmacher** [comment]
Hi @Makosak and @mradamcox, I've completed the google form for the new displacement index. Let me know if you have any questions about it. Dajoin made the shapefile and Chris wrote up the metadata. For visualization purposes, it should look like this site: https://displacement-risk.housingstudies.org/
