### ISSUE TITLE
Add Heat 2023 Max Temp to Chives

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/chicago-environment-explorer#132]
Requested by PRN, following review.

**Comment by mradamcox** [comment]
@jluiuc can you just let us know here when the data is ready? Then we can add it to the build, and @bodom0015 we'll do that on the existing PR here: https://github.com/GeoDaCenter/chicago-environment-explorer/pull/129 so that all of the variables are published at once.

**Comment by jluiuc** [comment]
@mradamcox @bodom0015 I've submitted the new max heat index variable and its updated metadata document through the submission form

**Comment by mradamcox** [comment]
Thanks @jluiuc we'll get to this soon! Appreciate the heads up.

**Comment by mradamcox** [comment]
@Makosak and @jluiuc, this variable is now in the production site, as well as your categorization updates. Can one of you check out the map and close this ticket if everything looks good to you?

**Comment by Makosak** [comment]
This looks great to me. One request; can we move up _Heat Indicators_ under _Air Quality_?

**Comment by mradamcox** [comment]
@makosak Unfortunately, reordering those list groups will take a little bit of effort, described here: https://github.com/GeoDaCenter/chicago-environment-explorer/issues/138, as they are currently just alphabetically listed. So I'm going to close this ticket now but we can reorder them in the future if we decide to implement that capability.
