### ISSUE TITLE
Add cooling centers as new layer

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/chicago-environment-explorer#146]
Requested by PRN Collaboration.

+ Include all cooling centers, categorize by type (ex. senior housing)
+ Develop as a Google Sheet, Lonette & PRN staff would update and manage long-term
+ Add as a new layer/overlay 

Should include 6 designated centers, then update with following:
https://data.cityofchicago.org/Health-Human-Services/Cooling-Centers-Map/cj7n-sh49

**Comment by Makosak** [comment]
Libraries should be included as a categorical group (they are already included in link above as a cooling center) -- we could re-use that later as a separate resource (to discuss with PRN)

**Comment by Makosak** [comment]
Confirmed that this is ready to be pushed to engineering tasks. Update to original goals:

- pull directly from: https://data.cityofchicago.org/Health-Human-Services/Cooling-Centers-Map/cj7n-sh49
- include all cooling centers, categorize by type visually.
- make the spray pads a more transparent/lighter call to make less visually strong, as these are least useful to elder populations or groups needing cooling on nights/weekends.
- ensure name, address, phone number, and hours are shown in pop-up window

**Comment by mradamcox** [comment]
One clarification, would this need to be a dynamic link to the Cooling Center data, a periodic update, or just a one-off export and import?

**Comment by Makosak** [comment]
I think a periodic update would be ideal -- for ex, checking weekly or
monthly? It's not likely to update regularly, but in case it does (in
response to a heat event) would be good to have a way to capture that info.

Short term, export/import could be fine as a working prototype
