### ISSUE TITLE
[Bug] Bin labels and color bars in legend don't match

### ISSUE THREAD

**Issue by mradamcox** [GeoDaCenter/chicago-environment-explorer#151]
**Describe the problem**

I was trying a few things out to see if I could get a better alignment for the new min/max labels in the legend (not easy!), and then realized that with certain variables there are way more color bars than labels. For example:

![image](https://github.com/GeoDaCenter/chicago-environment-explorer/assets/10427268/ac2690bf-8ccf-4fb2-a2d2-7a8749735253)

As you can see (and this is the main site before the addition of min/max labels) there are only 5 labels where there should be 7 (if min/max were added here, then there would be 9 labels total).

This must be a discrepancy between the `colorScale` and `bins` variables that are passed into the `Legend` component.

**Expected behavior**

`bins` and `colorScale` should be dependent on each other upstream of the Legend such that the discrepancy noted here won't exist.

There should be one label per break-point that divides one bin from the next. Additionally, per #130, there should be a label for the minimum value and the maximum value (this work is in progress in https://github.com/GeoDaCenter/chicago-environment-explorer/pull/140)

**Comment by bodom0015** [comment]
Fixed by #140 :+1:
