### ISSUE TITLE
Add geocoder to main map

### ISSUE THREAD

**Issue by Anthonyfq00** [GeoDaCenter/chicago-environment-explorer#154]
Please add exact street addresses to map. This will make searching areas a lot easier for the students

**Comment by Makosak** [comment]
May need to enable geocoding -- via Mapbox, https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/, @mradamcox to review

**Comment by Makosak** [comment]
Changing title of ticket to "add geocoder" on main map
