### ISSUE TITLE
Remove Link to Wild Onion

### ISSUE THREAD

**Issue by nofurtherinformation** [GeoDaCenter/chicago-environment-explorer#2]
The current link (on text "Like the wild onion") on the home page may encourage poaching, which is a major issue in forest preserves. Elsa raised this issue, and suggested the Illinois Wildflowers site as a possible alternative:

https://www.illinoiswildflowers.info/woodland/plants/wild_leek.htm

**Comment by Makosak** [comment]
updated it latest push.
