### ISSUE TITLE
Adding opportunities metric (w/i equity & assets framework)

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/chicago-environment-explorer#37]
Following conversations with Unite Us team; highlight places to plant trees for ex (could be index integrating a few measures?)

**Comment by Makosak** [comment]
Will add racial & ethnic groups as widgets & within pop-up info window. Updated to May milestone.

**Comment by Makosak** [comment]
@ssingh85 and @svijay77 I believe this was in process -- could you push to the dev branch or direct @mukeshchugani10 to the update? Thanks!

**Comment by Makosak** [comment]
Updating/clarifying : 

+ racial & ethnic groups as histogram widgets & as additional variables viewable within the pop-up info window
+ may need to connect with @Shubham to review UX components
+ goal is to make visible potential disparities and varying opportunities & environments across racial & ethnic groups, as a tool for advocacy

**Comment by Makosak** [comment]
@mukeshchugani10  to close

**Comment by mukeshchugani10** [comment]
Fixed in #81 . Closing now.
