### ISSUE TITLE
Add additional SDOH concepts

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/chicago-environment-explorer#43]
Per new NASA grant objectives, add the following using ACS 2018 data. Include as rows in pop-up windows, and widgets, and complete metadata integration:

Socio-economic and Demographic Variables:
(1) Overcrowding (persons per room and square footage per person); 
(2) Median rent and median home value; 
(3) Cost Burdened Renters and Owners (those that spend >30% of the monthly income on housing costs); 
(4) Percentage of foreign born population; 
(5) Average household size; 
(6) Percent family and non-family households; 
(7) Percent of the population with a four-year college degree.

**Comment by Makosak** [comment]
Update on 2/22 -- 
X (1) Overcrowding (persons per room and square footage per person); 
X (2) Median rent and median home value;
(3) Cost Burdened Renters and Owners (those that spend >30% of the monthly income on housing costs);
X (4) Percentage of foreign born population;
X (5) Average household size;
X (6) Percent family and non-family households;
X (7) Percent of the population with a four-year college degree.

**Comment by ssingh85** [comment]
Variables have been updated as "SDOH + demographics" excel file in HEROP folder.
