### ISSUE TITLE
Add displacement index

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/chicago-environment-explorer#47]

**Comment by Makosak** [comment]
Sent CSV to Sparsh, will incorporate by March deadline

**Comment by Makosak** [comment]
@ssingh85 will convert the CSV of displacement index to the public Google spreadsheet for back-end integration.

**Comment by Makosak** [comment]
Note that the source is DePaul Housing Institute, more info is here -- this should be included in the Metadata documentation: https://www.housingstudies.org/releases/mapping-displacement-pressure-chicago-2021/

**Comment by ssingh85** [comment]
Added "displacement index" excel file in DEPAUL folder.

**Comment by Makosak** [comment]
Sorry, mixed this up with the redlining piece for a moment! @ssingh85 don't forget to close out
