### ISSUE TITLE
Begin Community New Var Report for Review

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/chicago-environment-explorer#52]
Include new SDOH + demographic data (HEROP), redlining data (HEROP), and displacement index (DEPAUL). Each variable should include a short description, map (with jenks or quantile data classification), and histogram. Draft due by March 30; will refine and share with community 2 weeks later. Use Google Docs to start, but will fold into this repo when complete (as PDF).

**Comment by aishas2** [comment]
Google docs link: https://docs.google.com/document/d/1lA-p-p9fBfpxikJ4WMfCatXIfjvyk9910t0Xi4HuA5U/edit#
