### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by mradamcox** [GeoDaCenter/chicago-environment-explorer#63]
It's a (very) minor issue, but it would be nice to have a favicon on this site. Maybe this image from the animated logo (with transparent background instead of white): 
![image](https://github.com/GeoDaCenter/chicago-environment-explorer/assets/10427268/2a9a2283-2ca3-43e3-a106-cfcb9ad47c7e)

**Comment by Makosak** [comment]
Looks good to me! I like it.
