### ISSUE TITLE
Latine Community 

### ISSUE THREAD

**Issue by MarcAst24** [GeoDaCenter/chicago-environment-explorer#68]
On the community report page, the Latine community is missing on the west side. Notably, the Latino community is missing from most of the community pages.

**Comment by mradamcox** [comment]
The `demographic data.xlsx` spreadsheet needs to be revised. It does not have any column for `hispP` and the `otherP` column has suspiciously low numbers, it may be mislabeled.

The generated text content in the `/community` page must break the Race and Ethnicity row into two separate rows.

**Comment by mukeshchugani10** [comment]
Fixed in #77 . Closing now.
