### ISSUE TITLE
Histogram filters

### ISSUE THREAD

**Issue by MarcAst24** [GeoDaCenter/chicago-environment-explorer#69]
It's not obvious that the histogram is interactive. 

Additionally, it isn't entirely obvious what interacting with the filter actually shows the user. However, this is less important than making it so it is obvious the histogram can be interacted with.

**Comment by mradamcox** [comment]
Some work has been done on this, and is currently in the `dev` branch, but another look still needs to take place.

**Comment by mukeshchugani10** [comment]
Histogram bars have been re-designed with dotted lines and arrows. This can be a temporary fix for now and can be enhanced with a better design possibly in Spring 2024.

**Comment by mradamcox** [comment]
@MarcAst24 and @Makosak can you have a look at the current histogram filters when you get a chance so we can either 1) close this ticket, or 2) get some more specific tasks added to it for future reference?

**Comment by Makosak** [comment]
Closing for now -- works until we consider an updated approach in future!
