### ISSUE TITLE
Home Page -- Title Text

### ISSUE THREAD

**Issue by MarcAst24** [GeoDaCenter/chicago-environment-explorer#89]
**Issue**: Title text does not stand out aesthetically

**Recommendation**: Change title’s prominent text to accent color and bold the important keywords, keep paragraph text close to title text

**Rationale**: Draw more attention to the headlining content

**Comment by mradamcox** [comment]
closing, now tracked in https://github.com/GeoDaCenter/chicago-environment-explorer/issues/115
