### ISSUE TITLE
Home Page—Descending Order of tools

### ISSUE THREAD

**Issue by MarcAst24** [GeoDaCenter/chicago-environment-explorer#90]
**Issue**: Is the order (i.) Community Report, (ii.) Neighborhood map, (iii.) Resource Guide, on the website in descending order of click-through?

**Recommendation**: Consider reordering in descending order as per data from Google Analytics or similar

**Rationale**: Users scan pages in Z and F patterns, keeping most used pages from left to right is preferred

**Comment by mradamcox** [comment]
closing, now tracked in https://github.com/GeoDaCenter/chicago-environment-explorer/issues/115
