### ISSUE TITLE
Homepage— Promote Neighborhood map

### ISSUE THREAD

**Issue by MarcAst24** [GeoDaCenter/chicago-environment-explorer#91]
**Issue**: Is the neighborhood map the most used feature?

**Recommendation**: Promote the neighborhood location search bar to search for a location or zip code but also give an option to see all locations if the user does not want to type in anything specific

**Rationale**: Users can quickly query for the map they want to search instead of scrolling down

**Comment by mradamcox** [comment]
closing, now tracked in https://github.com/GeoDaCenter/chicago-environment-explorer/issues/115
