### ISSUE TITLE
Home page—Jumbotron improvements

### ISSUE THREAD

**Issue by MarcAst24** [GeoDaCenter/chicago-environment-explorer#92]
**Issue**: The jumbotron could be more visually engaging.

**Recommendation**: The page’s second section with the map previews showing PM2.5, vegetation, biodiversity, traffic, redlining, and asthma could be placed on the right side of the first section, beside the heading “Uncover the nature of Chicago's environment.

**Rationale**: Visuals can improve the overall aesthetic attractiveness of the landing page

**Comment by mradamcox** [comment]
closing, now tracked in https://github.com/GeoDaCenter/chicago-environment-explorer/issues/115
