### ISSUE TITLE
Resource guide— Resource verification

### ISSUE THREAD

**Issue by MarcAst24** [GeoDaCenter/chicago-environment-explorer#96]
**Issue**: The text indicating verification is buried at the bottom

**Recommendation**: Have the verification right under the title of the resource. (See [UX Audit google doc](https://docs.google.com/document/d/1ksUeDUJst-s_GU3Y_tPb3IqEDAujxCiw1xwfAUrvNio/edit?usp=sharing) for screenshot)

**Rationale**: Readers will quickly recognize the credibility of the resource before they read more about it.

**Comment by mradamcox** [comment]
Top item shows requested change, bottom is existing
![image](https://github.com/GeoDaCenter/chicago-environment-explorer/assets/10427268/26b99c84-7737-4fa8-a295-666d83b29781)

**Comment by Makosak** [comment]
All of the options here are credible; the verification is just an additional step we are including. May also not look as good when broken up this way, and may not be worth it for what is being provided. Recommend closing as not planned.
