### ISSUE TITLE
About—Standard & Submissions guidelines link

### ISSUE THREAD

**Issue by MarcAst24** [GeoDaCenter/chicago-environment-explorer#99]
**Issue**: In the link “Standards and Submission Guidelines”, the the Google doc has unresolved suggestions

**Recommendation**: Mark them as complete or edit and mark them as complete

**Rationale**: Present clean documents

**Comment by mradamcox** [comment]
@Makosak I think you're the best person with full edit permissions to this Google Doc to complete this task.

**Comment by mradamcox** [comment]
Completed.
